spring.datasource.url=jdbc:mysql://localhost:3306/book_store?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=StrongPassword!1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

server.servlet.context-path=/api

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/changelog-master.yaml

jwt.secret=vqwjeoqewojfqwiejifqwevijwoqifjq2oiwfjoijffewqfewqf
jwt.expiration=500000
